site_name: Langchain Training Material

nav:
  - Home: index.md

site_author: Sai Srinivas
site_description: >-
  DESCRIPTION


repo_name: saisrinivas-samoju/langchain_training
repo_url: https://github.com/saisrinivas-samoju/langchain_training


theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: 161f6d
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: red
      accent: lime
  
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/saisrinivas-samoju
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/sai-srinivas-samoju/

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  
  
plugins:
  - search

copyright: |
  &copy; 2024 <a href="https://github.com/saisrinivas-samoju"  target="_blank" rel="noopener">Sai Srinivas</a>

extra:
  generator: false