site_name: Langchain Training Material

nav:
  - Home: index.md
  - Setup: setup.md
  - Introduction: introduction.md
  - Model Connection: model_connection.md
  - Model IO: model_io.md
  - Retrieval: retrieval.md

site_author: Sai Srinivas
site_description: This website contains all the course materials and quick revision concepts.


repo_name: saisrinivas-samoju/langchain_training
repo_url: https://github.com/saisrinivas-samoju/langchain_training


theme:
  name: material
  font:
    text: Fira Sans
    code: Fira Code
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - content.code.copy
    - content.code.annotate
  language: en
  palette:
    - scheme: default
      toggle:
        # icon: material/toggle-switch-off-outline
        icon: material/weather-sunny
        name: Switch to dark mode
      # primary: 161f6d
      # accent: purple 
      # primary: indigo
      primary: red
      accent: indigo
      background: grey
    - scheme: slate 
      toggle:
        # icon: material/toggle-switch
        icon: material/weather-night
        name: Switch to light mode
      # primary: red
      # accent: lime
      primary: black
      accent: black
  icon:
      repo: fontawesome/brands/github
  custom.css: custom.css
    

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  # - pymdownx.superfences
  - pymdownx.mark
  - markdown.extensions.codehilite:
      noclasses: True
      pygments_style: perldoc
    # https://pygments.org/styles/
  
  
plugins:
  - search

copyright: |
  &copy; 2024 <a href="https://github.com/saisrinivas-samoju"  target="_blank" rel="noopener">Sai Srinivas</a>

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/saisrinivas-samoju
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/sai-srinivas-samoju/
  generator: false